/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */

import '@stencil/core';

declare global {
  namespace JSX {
    interface Element {}
    export interface IntrinsicElements {}
  }
  namespace JSXElements {}

  interface HTMLStencilElement extends HTMLElement {
    componentOnReady(): Promise<this>;
    componentOnReady(done: (ele?: this) => void): void;

    forceUpdate(): void;
  }

  interface HTMLAttributes {}
}


declare global {

  namespace StencilComponents {
    interface YooVirtualScroll {
      'disabled': boolean;
      'items': any;
      'text': string;
    }
  }

  interface HTMLYooVirtualScrollElement extends StencilComponents.YooVirtualScroll, HTMLStencilElement {}

  var HTMLYooVirtualScrollElement: {
    prototype: HTMLYooVirtualScrollElement;
    new (): HTMLYooVirtualScrollElement;
  };
  interface HTMLElementTagNameMap {
    'yoo-virtual-scroll': HTMLYooVirtualScrollElement;
  }
  interface ElementTagNameMap {
    'yoo-virtual-scroll': HTMLYooVirtualScrollElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      'yoo-virtual-scroll': JSXElements.YooVirtualScrollAttributes;
    }
  }
  namespace JSXElements {
    export interface YooVirtualScrollAttributes extends HTMLAttributes {
      'disabled'?: boolean;
      'items'?: any;
      'onButtonClicked'?: (event: CustomEvent<boolean>) => void;
      'text'?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }

export declare function defineCustomElements(window: any): void;